FROM docker.io/alpine

COPY status.sh /usr/bin/status.sh
COPY watch.sh /usr/bin/watch.sh

RUN apk add nano miniupnpc bash inotify-tools curl bind-tools jq

VOLUME [ "/etc/yggdrasil-network" ]

ENTRYPOINT [ "/bin/bash","/usr/bin/watch.sh" ]