FROM docker.io/alpine

COPY status.sh /usr/bin/status.sh
COPY upnp.sh /usr/bin/upnp.sh

RUN apk add nano miniupnpc bash inotify-tools curl bind-tools 

VOLUME [ "/etc/yggdrasil-network" ]

ENTRYPOINT [ "/bin/bash","/usr/bin/upnp.sh" ]