FROM docker.io/alpine

RUN apk add nano jq procps miniupnpc bash inotify-tools curl bind-tools 
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

COPY crawler /crawler
WORKDIR /crawler

RUN pip3 install -r requirements.txt

VOLUME [ "/etc/yggdrasil-network" ]

ENTRYPOINT ["/bin/bash", "/crawler/watch.sh" ]