# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
    branches:
      - SAM-43-ci-cd-workflow

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      dispatched:
        description: "Mark this invocation as a manual dispatch"
        required: false
        type: boolean
        default: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.dispatched || github.event.workflow_run.conclusion == 'success' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: release-info-${{ github.sha }}
          path: ./release-info

      - name: Set release info
        id: set-release-info
        run: |
          echo "::set-output name=commit::$(cat ./release-info/commit)"
          echo "::set-output name=id::$(cat ./release-info/id)"

      - name: balena finalize draft
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: >
            release finalize ${{ steps.set-release-info.outputs.id }}
          balena_cli_version: 14.3.1
