name: update-submodules

# Controls when the workflow will run
on:
  repository_dispatch:
    types:
      - push

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository of the submodule to update"
        required: true
        type: string

env:
  AUTO_UPDATE_LABEL: "auto-update-submodules"
  BASE_BRANCH: develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  find-open-pr:
    runs-on: ubuntu-latest

    outputs:
      AUTO_UPDATE_BRANCH: ${{ steps.find-open-pr.outputs.result }}

    steps:
      - name: Find open PR
        id: find-open-pr
        uses: actions/github-script@v6
        with:
          script: |
            const AUTO_UPDATE_LABEL = "${{ env.AUTO_UPDATE_LABEL }}"
            const prs = await github.rest.pulls.list({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.repository_name }}".split('/')[1],
                state: "open",
            })
            const branches = prs
              .filter(it => it.labels.find(label => label.name === AUTO_UPDATE_LABEL))
              .map(it => it.head.ref)
            if (branches.length > 1) {
              throw new Error(
                `More than one open PR with label ${AUTO_UPDATE_LABEL} found: ${branches.join(', ')}`
              )
            }
            return branches[0] ?? ''

  create-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: find-open-pr

    outputs:
      AUTO_UPDATE_BRANCH: ${{ steps.create-pr.outputs.AUTO_UPDATE_BRANCH }}

    steps:
      - name: Create pull request
        id: create-pr
        if: ${{ !needs.find-open-pr.outputs.AUTO_UPDATE_BRANCH }}
        run: |
          export BASE_BRANCH="${{ env.BASE_BRANCH }}"
          export NEW_BRANCH="auto-update-submodules-$BASE_BRANCH-$(($(date +%s%N)/1000000))"
          export AUTO_UPDATE_LABEL="${{ env.AUTO_UPDATE_LABEL }}"
          gh pr create -B "$BASE_BRANCH" -H "$NEW_BRANCH" --title 'Auto-update: submodules to develop' --body '' --label "$AUTO_UPDATE_LABEL"
          echo "AUTO_UPDATE_BRANCH=$NEW_BRANCH" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-submodules:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: [find-open-pr, create-pr]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get repository_dispatch repository name
        if: ${{ github.event.client_payload.repository }}
        run: |
          echo "REPOSITORY_NAME=${{ github.event.client_payload.repository }}" >> $GITHUB_ENV

      - name: Get workflow_dispatch repository name
        if: ${{ github.event.inputs.repository }}
        run: |
          echo "REPOSITORY_NAME=${{ github.event.inputs.repository }}" >> $GITHUB_ENV

      - name: Get find-open-pr output branch
        if: ${{ needs.find-open-pr.outputs.AUTO_UPDATE_BRANCH }}
        run: |
          echo "AUTO_UPDATE_BRANCH=${{ needs.find-open-pr.outputs.AUTO_UPDATE_BRANCH }}" >> $GITHUB_ENV

      - name: Get create-pr output branch
        if: ${{ needs.create-pr.outputs.AUTO_UPDATE_BRANCH }}
        run: |
          echo "AUTO_UPDATE_BRANCH=${{ needs.create-pr.outputs.AUTO_UPDATE_BRANCH }}" >> $GITHUB_ENV

      - name: Parse submodule path
        run: |
          export REPOSITORY_NAME="${{ env.REPOSITORY_NAME }}"
          export SUBMODULE_NAME=$(\
            git config --file .gitmodules --get-regexp url | \
              grep "$REPOSITORY_NAME" | \
              awk 'BEGIN{FS=OFS="."}{print $2}'\
          )

          echo "SUBMODULE_PATH=$(git config --file .gitmodules --get "submodule.$SUBMODULE_NAME.path")" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2
          ref: ${{ env.AUTO_UPDATE_BRANCH }}

      - name: Update submodules
        run: |
          export BASE_BRANCH="${{ env.BASE_BRANCH }}"
          export PWD=$(pwd)

          cd "${{ env.SUBMODULE_PATH }}"
          git switch "$BASE_BRANCH"
          git pull
          cd "$PWD"

          git add .
          git commit -m "Auto-update: submodules to $BASE_BRANCH"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.HERAKLES_TOKEN }}
